config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  get 'about' => 'about#index'

  resources :books 
  resources :authors 
  resources :publishers 
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  belongs_to :author
  belongs_to :publisher
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  validates :name, presence: true, length: {minimum: 3}
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books

  validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  
  def index
    @page_title = 'About Us'
  end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add New Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = "Author #{@author.first_name} Created"
      redirect_to authors_path(@author)
    else
      flash[:alert] = "Author not created."
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(author_params)
      flash[:notice] = "Updated"
      redirect_to authors_path
    else
      flash[:alert] = "Not updated"
      render 'edit'
    end
  end

  def edit
    @author = Author.find(params[:id])
    @categories = Category.all
  end

  def destroy
  end

  def index
    @authors = Author.all
    @categories = Category.all
  end

  def show
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'All Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book #{@book.title} Created!"
      redirect_to root_path
    else
      flash[:alert] = "Book not created"
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:notice] = "Book #{@book.title} Successfully updated"
      redirect_to root_path
    else
      flash[:alert] = "Sorry, #{@book.title} ot updated."
      render 'edit'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @categories = Category.all
    @authors = Author.all
    @publishers = Publisher.all
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book #{@book.title}, successfully deleted!"
    redirect_to root_path
  end

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @bookname = @book.author.first_name + ' ' + @book.author.last_name
    @categories = Category.all
  end

  private

  def book_params
    params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :price, :buy, :format, :excerpt, :pages, :year, :coverpath)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add New Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category #{@category.name} Created"
      redirect_to categories_path(@category)
    else
      flash[:alert] = "Category not created."
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:notice] = "Updated Successfully"
      redirect_to categories_path
    else
      flash[:notice] = "Not updated"
      render 'edit'
    end
  end

  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category #{@category.name} successfully deleted."
    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books = @category.books
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add New Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = "Publisher #{@publisher.name} Created"
      redirect_to publishers_path(@publisher)
    else
      flash[:alert] = "Publisher not created."
      render 'new'
    end
  end

  def update
    @publisher = Publisher.find(params[:id])
    if @publisher.update_attributes(publisher_params)
      flash[:notice] = "Updated"
      redirect_to publishers_path
    else
      flash[:alert] = "Error"
      render 'edit'
    end
  end

  def edit
    @publisher = Publisher.find(params[:id])
    @categories = Category.all
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy
    flash[:notice] = "Successfully deleted..."
    redirect_to publishers_path
  end

  def index
    @publishers = Publisher.all
    @categories = Category.all
  end

  def show
  end

  private

  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Poutine iPhone poke, kogi chicharrones lyft migas actually hammock. Mumblecore gentrify squid, street art irony organic direct trade distillery pabst pug everyday carry raclette sriracha. You probably haven't heard of them man bun portland roof party flannel, 3 wolf moon subway tile man braid. Cray enamel pin shoreditch la croix forage listicle. Air plant direct trade viral retro photo booth slow-carb. Cliche chambray hashtag chartreuse selvage forage viral authentic, lumbersexual tousled normcore locavore gluten-free truffaut. Heirloom lomo kickstarter cred selfies.

Next level mumblecore XOXO, irony church-key YOLO health goth VHS. Craft beer kitsch YOLO vice. Shoreditch pug banjo chillwave, tbh fixie hella literally. Marfa vegan deep v aesthetic, hashtag distillery sartorial art party plaid. Craft beer franzen hella air plant organic stumptown farm-to-table pour-over. 3 wolf moon activated charcoal vaporware 8-bit affogato, cronut mustache kale chips kitsch authentic drinking vinegar. Jean shorts seitan pitchfork, art party pickled franzen af tousled cliche farm-to-table roof party fixie typewriter.</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h2>Edit Author</h2>

<%= form_for @author do |f| %>

  <% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <%= f.submit 'Submit', class: "btn btn-primary"  %>
  <%= link_to 'Cancel', authors_path, class: "btn btn-default" %>
<% end %>

app/views/authors/index.html.erb
<h2>Authors</h2>

<table class="table table-striped">
  <tr>
    <th>Author Name</th>
    <th>Actions</th>
  </tr>

  <% @authors.each do |author| %>
    <tr>
      <td><%= author.first_name %> <%= author.last_name %></td>
      <td><%= link_to 'Edit', edit_author_path(author.id), class: 'btn btn-primary' %> <%= link_to 'Delete', author_path(author.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>

app/views/authors/new.html.erb
<h2>Add New Author</h2>

<%= form_for @author do |f| %>

  <% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <%= f.submit 'Submit', class: "btn btn-primary"  %>
  <%= link_to 'Cancel', authors_path, class: "btn btn-default" %>
<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <% @book.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :isbn %>
    <%= f.text_field :isbn, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select One'}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :publisher %>
    <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :format %>
    <%= f.text_field :format, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :year %>
    <%= f.text_field :year, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :coverpath %>
    <%= f.text_field :coverpath, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :excerpt %>
    <%= f.text_area :excerpt, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :pages %>
    <%= f.number_field :pages, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :buy %>
    <%= f.text_field :buy, class: "form-control" %>
  </div>

  <%= f.submit 'Submit', class: "btn btn-primary" %>
  <%= link_to 'Cancel', books_path, class: "btn btn-default" %>
<% end %>

app/views/books/index.html.erb
<div id="books-index">
  <% @books.each_slice(4) do |book| %>
    <div class="row">
      <% book.each do |book| %>
        <div class="col-md-3 col-sm-3">
          <h3><%= book.title %></h3>
          <%= image_tag(book.coverpath)  %>
          <%= link_to 'Read more', book_path(book), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>Add New Book</h1>

<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <% @book.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :isbn %>
    <%= f.text_field :isbn, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select One'}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :publisher %>
    <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :format %>
    <%= f.text_field :format, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :year %>
    <%= f.text_field :year, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :coverpath %>
    <%= f.text_field :coverpath, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :excerpt %>
    <%= f.text_area :excerpt, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :pages %>
    <%= f.number_field :pages, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :buy %>
    <%= f.text_field :buy, class: "form-control" %>
  </div>

  <%= f.submit 'Submit', class: "btn btn-primary" %>
  <%= link_to 'Cancel', books_path, class: "btn btn-default" %>
<% end %>

app/views/books/show.html.erb
<div id="books-show">
  <h2><%= @book.title%></h2>
  <div class="books-show-left">
    <%= image_tag(@book.coverpath, size: '200x250')  %>
  </div>
  <div class="book-show-right">
    <h3>Book Info:</h3>
    <ul>
      <li><strong>Category: </strong><%= @book.category.name %></li>
      <li><strong>Author: </strong><%= @bookname %></li>
      <li><strong>Publisher: </strong><%= @book.publisher.name %></li>
      <li><strong>Price: </strong><%= @book.price %></li>
    </ul>
    <%= link_to 'Buy on eBay', @book.buy, class: "btn btn-success", target: '_blank' %>
  </div>
  <div class="clearfix"></div>
  <h4>Description:</h4>
  <p><%= @book.excerpt %></p>

  <h3>Admin Functions</h3>
  <%= link_to 'Edit', edit_book_path(@book.id) %> | <%= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>

  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <%= f.submit 'Submit', class: "btn btn-primary" %>
  <%= link_to 'Cancel', categories_path, class: "btn btn-default" %>
<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<table class="table table-striped">
  <tr>
    <th>Category Name</th>
    <th>Actions</th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to 'Edit', edit_category_path(category.id), class: 'btn btn-primary' %> <%= link_to 'Delete', category_path(category.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h2>Add new Category</h2>

<%= form_for @category do |f| %>

  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <%= f.submit 'Submit', class: "btn btn-primary" %>
  <%= link_to 'Cancel', categories_path, class: "btn btn-default" %>
<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<div id="books-index">
  <% @books.each_slice(4) do |book| %>
    <div class="row">
      <% book.each do |book| %>
        <div class="col-md-3 col-sm-3">
          <h3><%= book.title %></h3>
          <%= image_tag(book.coverpath) %>
          <%= link_to 'Read More', book_path(book), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= @page_title ? @page_title : 'Welcome' %> | The BookStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Home', root_path %></li>
            <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'About', about_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New <span class="caret"></span></a>
              <ul class="dropdown-menu navbar-right">
                <li><%= link_to 'Book', new_book_path %></li>
                <li><%= link_to 'Category', new_category_path %></li>
                <li><%= link_to 'Author', new_author_path %></li>
                <li><%= link_to 'Publisher', new_publisher_path %></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage<span class="caret"></span></a>
              <ul class="dropdown-menu navbar-right">
                <li><%= link_to 'Categories', categories_path %></li>
                <li><%= link_to 'Authors', authors_path %></li>
                <li><%= link_to 'Publishers', publishers_path %></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <header>
      <div class="container">
        <h1>BookStore <small><%= @page_title ? @page_title : 'Welcome' %></small></h1>
      </div>
    </header>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <% if flash[:notice] %>
              <div class="alert alert-success"><%= flash[:notice] %></div>
            <% end %>
            <% if flash[:alert] %>
              <div class="alert alert-danger"><%= flash[:alert] %></div>
            <% end %>

            <%= yield %>
          </div>
          <div class="col-md-4">
            <%= render 'partials/sidebar' %>
          </div>
        </div>
      </div>
    </section>

    <footer>
      <div class="container">
        <p>Copyright &copy; 2016, All rights reserved</p>
      </div>
    </footer>

  </body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
  <div class="well">
    <h3>Location info</h3>
    <ul>
      <li>The Bookstore</li>
      <li>Phone: 8 922 355 12 15</li>
      <li>Email: bookstore@gmail.com</li>
    </ul>
  </div>
<% end %>
<% if params[:controller] == 'books' && params[:action] == 'index' || 'show' %>
  <div class="list-group">
    <% @categories.each do |category| %>
      <%= link_to category.name, category_path(category.id), class: 'list-group-item' %>
    <% end %>
  </div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h2>Edit Publisher</h2>

<%= form_for @publisher do |f| %>
  <% if @publisher.errors.any? %>
    <% @publisher.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', publishers_path, class: 'btn btn-default' %>
<% end %>

app/views/publishers/index.html.erb
<h2>Publishers</h2>

<table class="table table-striped">
  <tr>
    <th>Publisher Name</th>
    <th>Actions</th>
  </tr>

  <% @publishers.each do |publisher| %>
    <tr>
      <td><%= publisher.name %></td>
      <td><%= link_to 'Edit', edit_publisher_path(publisher.id), class: 'btn btn-primary' %> <%= link_to 'Delete', publisher_path(publisher.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>

app/views/publishers/new.html.erb
<h2>Add New Publisher</h2>

<%= form_for @publisher do |f| %>
  <% if @publisher.errors.any? %>
    <% @publisher.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', publishers_path, class: 'btn btn-default' %>
<% end %>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>